-- SQLite/PostgreSQL-compatible baseline for the structured investigation store.
CREATE TABLE IF NOT EXISTS cases (
  id VARCHAR(64) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'Open',
  priority VARCHAR(32) NOT NULL DEFAULT 'Medium',
  summary TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS evidence (
  id VARCHAR(64) PRIMARY KEY,
  case_id VARCHAR(64) NOT NULL REFERENCES cases(id),
  title VARCHAR(255) NOT NULL,
  type VARCHAR(64) NOT NULL,
  notes TEXT NOT NULL DEFAULT '',
  confidence REAL,
  source TEXT NOT NULL DEFAULT '',
  metadata_json TEXT NOT NULL DEFAULT '{}'
);
CREATE TABLE IF NOT EXISTS events (
  id VARCHAR(64) PRIMARY KEY,
  case_id VARCHAR(64) NOT NULL REFERENCES cases(id),
  time TIMESTAMP NOT NULL,
  label VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL DEFAULT '',
  source_evidence_id VARCHAR(64) REFERENCES evidence(id)
);
CREATE TABLE IF NOT EXISTS relations (
  id INTEGER PRIMARY KEY,
  case_id VARCHAR(64) NOT NULL REFERENCES cases(id),
  source VARCHAR(64) NOT NULL,
  target VARCHAR(64) NOT NULL,
  label VARCHAR(64) NOT NULL
);
CREATE TABLE IF NOT EXISTS rankings (
  id VARCHAR(64) PRIMARY KEY,
  case_id VARCHAR(64) NOT NULL REFERENCES cases(id),
  label VARCHAR(255) NOT NULL,
  score REAL NOT NULL,
  reason TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS contradictions (
  id VARCHAR(64) PRIMARY KEY,
  case_id VARCHAR(64) NOT NULL REFERENCES cases(id),
  severity VARCHAR(32) NOT NULL,
  summary TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS audit_log (
  id INTEGER PRIMARY KEY,
  at TIMESTAMP NOT NULL,
  actor VARCHAR(128) NOT NULL,
  action VARCHAR(128) NOT NULL,
  target VARCHAR(128) NOT NULL
);
